# Этап сборки
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /api ./cmd/api

# Финальный образ
FROM alpine:3.21
RUN apk add --no-cache ca-certificates curl
COPY --from=builder /api /api
COPY internal/config/configs/ /internal/config/configs/
EXPOSE 8080

HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:8080/health || exit 1

CMD ["/api"]
